### ISSUE TITLE
Stalemate causes game to continue forever

### ISSUE THREAD

**Issue by GaryHilares** [kcoder63/SuperMaxioCheckers_snakes-hackers#5]
**Describe the bug**
If the game results in a stalemate where the human player cannot move any piece, the game won't stop. Instead, it will keep running forever and will not declare a winner.

**To Reproduce**
1. Run the game.
2. Somehow get to a position where is your turn and you cannot move any piece.
3. Now the game will continue running forever.

**Expected behavior**
The rules of checkers state that if a game is stalemate, the player who has the turn loses. In this case, the human player should lose.

**Screenshots**
Red to move.
![SuperMarioCheckers_Issue#5_Image1](https://user-images.githubusercontent.com/46727048/115322975-c6cf6880-a14c-11eb-8095-b0792b3f0c51.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Although it probably happens in any OS).

**Comment by starlightknown** [comment]
wait was this solved?

**Comment by GaryHilares** [comment]
No, this was not solved.

**Comment by starlightknown** [comment]
okay I'll check this out soon

**Comment by GaryHilares** [comment]
I have just noticed that this also can happen when you lose.
![SuperMarioCheckers_Issue#5_Image2](https://user-images.githubusercontent.com/46727048/115411148-d84e5a00-a1b8-11eb-901f-022d844f9d73.png)

**Comment by starlightknown** [comment]
issue fixed by #14

**Comment by GaryHilares** [comment]
I have just checked this and the error is still present in the latest version of the main branch.
![image](https://user-images.githubusercontent.com/46727048/116787988-e16ae100-aa6c-11eb-90c8-1e02d9de8e25.png)

**Comment by starlightknown** [comment]
That can't be, do you see a message on your screen when you start the game with rules and when it ends a winner message should be displayed

**Comment by GaryHilares** [comment]
The message in the start of the game appears. The winner message appears when you capture all your opponent pieces. However, it does not appear when you get stalemated. I'm testing if it appears when you stalemate your opponent.

**Comment by starlightknown** [comment]
Ah thank you, I'm kinda less on time here so trying to fix all the bugs. This'll help
